version: '3.7'

services:

  db:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_DB: vertx-lab
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - vertx-lab-data-local:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  vertx-lab-data-local:
